# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codeset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeen', models.CharField(max_length=200)),
                ('codezh', models.CharField(max_length=200)),
                ('sina', models.CharField(max_length=200, null=True)),
                ('maincontract', models.CharField(max_length=200, null=True)),
                ('sbreed', models.CharField(max_length=200, unique=True)),
                ('market', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('9', '9')], max_length=2)),
                ('hassignal', models.BooleanField(default=False)),
                ('nighttrade', models.BooleanField(default=True)),
                ('hold', models.BooleanField(default=False)),
                ('actived', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Investingset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('namezh', models.CharField(max_length=200, null=True)),
                ('url', models.URLField(null=True)),
                ('category', models.CharField(max_length=200)),
                ('actived', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ladon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('no', models.IntegerField(null=True)),
                ('tradeno', models.IntegerField(null=True)),
                ('holdvar', models.IntegerField(default=0)),
                ('holdvarstrength', models.FloatField(default=0)),
                ('corelation', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Codeset')),
            ],
        ),
        migrations.CreateModel(
            name='Marketurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.IntegerField()),
                ('daily', models.CharField(max_length=200)),
                ('minute', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeno', models.IntegerField(null=True)),
                ('buyno', models.IntegerField(null=True)),
                ('sellno', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('buyposition', models.IntegerField(default=0)),
                ('buyvar', models.IntegerField(default=0)),
                ('tradeposition', models.IntegerField(default=0)),
                ('tradevar', models.IntegerField(default=0)),
                ('sellposition', models.IntegerField(default=0)),
                ('sellvar', models.IntegerField(default=0)),
                ('date', models.DateField(null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Codeset')),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('res', models.IntegerField(null=True)),
                ('resnew', models.IntegerField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Codeset')),
            ],
        ),
        migrations.CreateModel(
            name='Pricefreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('lastclose', models.FloatField(null=True)),
                ('buy', models.FloatField(null=True)),
                ('sell', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('avg', models.FloatField(null=True)),
                ('settle', models.FloatField(null=True)),
                ('buyvolume', models.IntegerField(null=True)),
                ('sellvolume', models.IntegerField(null=True)),
                ('hold', models.IntegerField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Codeset')),
            ],
        ),
        migrations.CreateModel(
            name='Proxyip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
                ('port', models.PositiveIntegerField(null=True)),
                ('area', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('speed', models.PositiveIntegerField(null=True)),
                ('checktime', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quandlset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('source', models.CharField(default='CHRIS', max_length=20)),
                ('exchange', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('namezh', models.CharField(max_length=20, null=True)),
                ('months', models.CharField(max_length=20, null=True)),
                ('quandlcode', models.CharField(max_length=20)),
                ('depth', models.PositiveIntegerField(default=1)),
                ('actived', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(choices=[('1', '1'), ('0', '0'), ('-1', '-1')], default=0, max_length=2)),
                ('cci', models.CharField(choices=[('1', '1'), ('0', '0'), ('-1', '-1')], default=0, max_length=2)),
                ('kdj', models.CharField(choices=[('1', '1'), ('0', '0'), ('-1', '-1')], default=0, max_length=2)),
                ('macd', models.CharField(choices=[('1', '1'), ('0', '0'), ('-1', '-1')], default=0, max_length=2)),
                ('strength', models.IntegerField(null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Codeset')),
            ],
        ),
    ]
